### ISSUE TITLE
Sort by recent

### ISSUE THREAD

**Issue by alexjj** [jackbaty/Books#1]
Definitely a personal preference but I think sorted by most recently read is better 😄

Using some logic, if I revisit your list in a few months time it's because I want to see what books you've read since the last time I visited. I have to scroll all the way to the bottom to find out, and that's another task in my day that needs logging in 6 independent knowledge gardens. 😅

**Comment by jackbaty** [comment]
This is so weird because I was _just this morning_ thinking of how I might sort them reversed! Consider this on the `planned` list :)
